version: '3.9'
services:
  rabbitmq:
    image: "rabbitmq:3.9-management"  # Use the RabbitMQ image with management plugin
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: "yourusername"  # Replace with your desired username
      RABBITMQ_DEFAULT_PASS: "yourpassword"  # Replace with your desired password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist data between container restarts

volumes:
  rabbitmq_data: